services:
  fastapi:
    build:
      context: ./questions-service
      dockerfile: Dockerfile
    # ports:
      # - "8085:8080" # No need for this in production if docker compose is used, {SERVICE_NAME} will point to the correct ip
    depends_on:
      postgres:
        condition: service_started
    environment:
      # Set DB_URL to connect FastAPI to the PostgreSQL container
      - DB_URL=postgresql://admin:admin@postgres:5432/pp-crud
    working_dir: /questions-service  # Set the working directory for FastAPI

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    # ports:
      # - "3001:3001" # For debugging, remember to delete in production
    
  nextjs:
    build:
      context: ./peerprep
      dockerfile: Dockerfile
    # ports:
    #   - "3005:3000"
    environment:
      - QUESTION_API_URL=http://fastapi:8080
      - USER_API_URL=http://user-service:3001
    networks:
      - caddy
      - default
    labels:
      caddy: "peerprep.ginloy.com"
      caddy.route.1_import: peerprep_auth
      caddy.route.2_handle_path: '/api/match*'
      caddy.route.2_handle_path.reverse_proxy: matching-service:8080
      caddy.route.3_reverse_proxy: "{{upstreams http 3000}}"

  matching-service:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    # ports:
    #   - "8086:8080"
    networks:
      - default
      - caddy

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pp-crud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
      # - "5433:5432" # No need for this

volumes:
  postgres_data:

networks:
  caddy:
    external: true
