import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import MainIcon from '@/icons/MainLogo.svg'
import Image from "next/image";
import '@mantine/core/styles.css'
import { AppShell, ColorSchemeScript, MantineProvider } from "@mantine/core";
import Header from "@/components/header";
import Shell from "@/components/shell";
import { currentUser } from "@/actions/user";
import { Notifications } from "@mantine/notifications";
import '@mantine/notifications/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser()

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
          <MantineProvider defaultColorScheme="dark">
            <Notifications />
            <Shell children={children} user={user} />
          </MantineProvider>
      </body>
    </html>
  );
}
